name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -sL https://get.sonarsource.com/sonarcloud-cli-linux -o sonarcloud-cli
          chmod +x sonarcloud-cli
          ./sonarcloud-cli analyze --project "shahyesha_git" -Dsonar.organization="shahyesha"
